### ISSUE TITLE
Installation through Carthage

### ISSUE THREAD

**Issue by jb2b38** [nighthawk/ASPolylineView#5]
Trying to move from manual file importation to managing dependencies with Carthage, I'm having trouble installing ASPolyline for iOS in a Swift 4 project.

I've had Carthage build the .framework file, dropped it under the Linked frameworks and Libraries of my project, added path to the framework in the run script of my build phases but I get the following two errors:

'ASPolylineView/ASPolylineRenderer.h' file not found (from the framework's headers file)
And from my files, import ASPolylineView results in : Could not build Objective-C module 'ASPolylineView'

I've tried cleaning the derived data folder, cleaning the project, but my attempts failed.
Could be a beginner's question as I've only followed [this RayWenderlich tutorial ](https://www.raywenderlich.com/165660/carthage-tutorial-getting-started-2) to use Carthage, but reading the official Carthage documentation didn't help either.

Thanks for your support.

EDIT: I've faced this issue after changing umbrella header "ASPolylineView.h" to "ASPolylineView-iOS.h" in the module.modulemap file, as I've had the message : Umbrella header 'ASPolylineView.h' not found.

**Comment by nighthawk** [comment]
I haven't yet used this project as a Carthage framework in another project myself, but it should be compatible with Carthage. I've added a Carthage-compatible release here that includes the `.framework` file: https://github.com/nighthawk/ASPolylineView/releases 

To you this you should add this line to your `Cartfile`:

`github "nighthawk/ASPolylineView"`

And then run `carthage update --platform iOS`.

Do you still have issues when using these steps, @jb2b38?

**Comment by jb2b38** [comment]
Yes, that's the steps I've followed. I've got the same issue when installing it from the provided zipped file though, so I assume we've built it the same way.

**Comment by nighthawk** [comment]
Ok, I'm taking a look if I can reproduce/fix it.

**Comment by nighthawk** [comment]
Found the issue. Will deploy a new release shortly. The cause was that the header files were marked to set to "Project" rather than "Public".

**Comment by nighthawk** [comment]
Done: [https://github.com/nighthawk/ASPolylineView/releases/tag/v1.0.1](v1.0.1). Worked in my test. Hopefully it works for you, too. And thanks for raising the issue!

**Comment by jb2b38** [comment]
Yes, it works. Thanks for being so reactive! :)
