### ISSUE TITLE
Unknown receiver ASPolylineView

### ISSUE THREAD

**Issue by jb2b38** [nighthawk/ASPolylineView#6]
Me again :)

Install through Carthage is now working and I can import the framework without problem, but I can't use it.

When doing import ASPolylineView, I have no more error message, but when I declare a variable like this : 
var test : ASPolylineView
I get the message "Use of undeclared type 'ASPolylineView'".

I've opened the PolylineExample Xcode project, and face the same issue when compiling : 
ASViewController.h line 56 : Unknown receiver 'ASPolylineView'; did you mean 'MKPolylineView'?

**Comment by nighthawk** [comment]
Indeed very strange. I'm looking into it... Never seen Xcode behave this way before. I suspect it's due to the project file being a bit older.

**Comment by nighthawk** [comment]
Ok, figured it out. That `#if` is the cause:

`#if __IPHONE_OS_VERSION_MIN_REQUIRED < __IPHONE_7_0`

Since iOS 8 `[AS|MK]PolylineRenderer` is what you should generally use, not `[AS|MK]PolylineView`. Xcode 9 is now setting the minimum version to iOS 8, so that class is, poof, gone when building with Xcode 9 which is causing the issues you're seeing. I'll restore the class and use a deprecation warning instead.

**Comment by jb2b38** [comment]
Yes, I'll have another problem then, I tried to import the renderer instead of the view at first try, but I get this error : No such module 'ASPolylineRenderer'. No problem importing the ASPolylineView though.

**Comment by jb2b38** [comment]
![capture d ecran 2017-09-23 a 19 49 23](https://user-images.githubusercontent.com/16371875/30775635-5c88ccf4-a098-11e7-8ea3-a61cc323d774.png)
The header does not seem to be exposed in the framework here.

**Comment by jb2b38** [comment]
![capture d ecran 2017-09-23 a 19 49 23](https://user-images.githubusercontent.com/16371875/30775652-98a82b76-a098-11e7-82c2-ecc03f1d75cb.png)
The header is properly included, so I don't get why I get the error.

**Comment by nighthawk** [comment]
Latest theory: The (Carthage) framework gives preference to "ASPolylineView.h" rather than the umbrella header "ASPolylineView-iOS.h" and it therefore can't find `ASPolylineRenderer` class.

If I add an `#import "ASPolylineRenderer.h"` to "ASPolylineView.h" it indeed seems to fix it.

**Comment by nighthawk** [comment]
Try this: https://github.com/nighthawk/ASPolylineView/releases/tag/v1.0.2

**Comment by jb2b38** [comment]
I downloaded v1.0.2 and can see the new header inclusion in the framework, but Xcode still complains.
I look into it a bit more to give you details if anything catches my attention.

**Comment by jb2b38** [comment]
Mmm, I spoke too quickly. I only need to import ASPolylineView to use the View AND the Renderer.
Thanks :)

**Comment by nighthawk** [comment]
Great! Can understand the confusion. Naming a module/framework after a class is definitely not the best idea ;)
